window.onload = init;
var vetParole = [
    "allinone",
    "servizio",
    "abbigliamento",
    "salute",
    "museo",
    "alimentare",
    "persona",
    "ristorazione",
    "stato",
    "trasporto",
    "mobile",
    "cartoleria",
    "automobile",
    "web",
    "elettronica",
    "intrattenimento",
    "banca",
    "azienda",
    "piante",
    "igiene e bellezza",
    "casa",
    "telefonia",
    "assicurare",
    "grafica pubblicitaria",
    "bolletta",
    "luoghi di culto",
    "parco",
    "libreria",
    "mestiere",
    "nonni",
    "madrina",
    "zia",
    "padre",
    "madre",
    "fratello",
    "sorella",
    "parenti",
    "amico",
    "amici",
    "compagno",
    "me",
    "gruppo",
    "trenitalia",
    "mercato'",
    "coop",
    "ikea",
    "posta",
    "amazon",
    "altro",
    "bar da pino ",
    "italo",
    "ryanair",
    "pizzeria corsaro",
    "montello",
    "il garil",
    "ottico",
    "coopvoce",
    "miur",
    "panetteria",
    "restiani",
    "bragas",
    "presto fresco",
    "distributore",
    "farmacia",
    "macellai",
    "altro sito",
    "ristorante giapponesese ",
    "carrefour",
    "in's",
    "gastronomia",
    "gtt",
    "negozio di musica ",
    "mi scusi",
    "trony",
    "bar",
    "alcott",
    "mef",
    "bene banca",
    "canale sarmassa",
    "supermercato",
    "narzole20",
    "chiesa",
    "ok market",
    "m** bun",
    "mediaworld",
    "unieuro",
    "esca",
    "terranova",
    "tutto capsule",
    "pizzeria",
    "amsterdam chips",
    "telesio",
    "teatro regio",
    "ospedale carle e santa croce ",
    "crai",
    "ristorante",
    "rifugio",
    "ospedale",
    "ristorante greco ",
    "residence",
    "spiaggia",
    "flower burger",
    "siculo",
    "old wild west",
    "kfc",
    "lidl",
    "salone del libro",
    "musei piemonte e valle d' aosta ",
    "penny",
    "pub",
    "bubble tea",
    "koko",
    "sottotono",
    "h&amp;m",
    "netflix",
    "fioraio",
    "macchinetta",
    "caddy",
    "booking",
    "airbnb",
    "altervista",
    "aruba",
    "dentista",
    "ovs",
    "zara",
    "bershka",
    "proprietario",
    "kebab",
    "spotify",
    "conad",
    "pasticceria",
    "alcyon",
    "ristorante marocchino ",
    "easyjet",
    "panetteria brungaj",
    "ristorante cinese ",
    "cinema",
    "ferramenta",
    "agenzia",
    "caffè an.sel",
    "asselle mobili ",
    "bocciofila",
    "parcheggio",
    "pam",
    "notaio",
    "proloco",
    "sncf",
    "leroy merlin",
    "dan john",
    "ishu&egrave;",
    "sushi jin yuan",
    "eurospin",
    "mega",
    "dschola",
    "kasanova",
    "decathlon",
    "piazzaitalia",
    "g. vallauri",
    "terme",
    "mercatino",
    "autostrada",
    "pala vela",
    "tassa automobilistica",
    "scarpe & scarpe",
    "ristorante persiano ",
    "atm",
    "idraulico",
    "elettricista",
    "mercato in piazza",
    "casa arcobaleno ",
    "museo storico",
    "monastero",
    "castello",
    "kiabi",
    "sapore di mare",
    "ristorante peruviano ",
    "burger king",
    "edicola",
    "tabaccaio",
    "fortezza",
    "museo archeologico",
    "piumè",
    "upim",
    "inps",
    "esselunga",
    "flying tiger",
    "teatro astra",
    "conbipel",
    "kayak",
    "sushi kata radja",
    "renfe",
    "google",
    "libero.it",
    "assicurazione vittoria ",
    "canva",
    "discord",
    "disney plus",
    "ebay",
    "enel",
    "facebook",
    "github",
    "instagram",
    "raiplay",
    "mediaset play",
    "siae",
    "microsoft",
    "poste id",
    "overleaf",
    "pixartprinting",
    "sky",
    "tim",
    "eni plenitude",
    "clienti.italgas.it",
    "linkedln",
    "valtis.infosys.it",
    "coop librett ",
    "openhouse",
    "aeroporto",
    "treno",
    "corvo rosso",
    "the isle of skye pub",
    "museo taurino",
    "muvim centrum",
    "museo della preistoria",
    "museo delle belle arti",
    "torres de serrans",
    "museo de la almoina",
    "torres de quart",
    "museo di arte moderna",
    "giardino botanico",
    "acquario",
    "museo delle scienze",
    "bioparco",
    "giardino",
    "mercato centrale",
    "la banca della seta",
    "murales",
    "casa museo ",
    "basilica",
    "cattedrale",
    "ristorante self - service",
    "palazzo reale",
    "museo da arte ",
    "bus",
    "articoli regalo",
    "ricordare",
    "lavatrice",
    "asciugatrice",
    "doccia",
    "aneddoto",
    "film",
    "canzone",
    "spettacolo",
    "attore",
    "cantante",
    "pianta",
    "vacanza al mare ",
    "camminare",
    "spettacolo teatrale ",
    "visita",
    "vacanza al lago ",
    "carnevale",
    "serie tv",
    "aereo",
    "check in",
    "spesa",
    "pranzo",
    "cena",
    "aperitivo",
    "colazione",
    "regalo",
    "festa",
    "comprat regalo ",
    "comprat scarpe ",
    "comprat abbigliamento ",
    "comprat per sfizio ",
    "vacanza",
    "cura",
    "presi in prestundefinedo ",
    "imprestati",
    "restituzion prestundefinedo ",
    "pagato servizio",
    "viaggio",
    "multa",
    "gelato",
    "ripetizioni",
    "bollo",
    "stipendio",
    "consulenza",
    "aiutare",
    "commissione",
    "tassa",
    "carburante",
    "ricarica",
    "rimborso",
    "divisione pagamento",
    "donazione",
    "necessità",
    "interessare",
    "lavoro",
    "risparmi",
    "biglietto",
    "affitto",
    "mutuo",
    "spese condominiali",
    "acqua",
    "gas",
    "energia",
    "passaggio di conto ",
    "recupero investimento",
    "bilancio manuale",
    "pattinaggio",
    "ristrutturazione",
    "sigarette",
    "acconto",
    "bevanda",
    "pedicure",
    "ricarica cassa comune ",
    "saldare",
    "abbonamento",
    "cioccolata",
    "giardinaggio",
    "trattamento fine rapporto",
    "evento",
    "prodotto alimentare ",
    "alberghiero",
    "social network",
    "negozio online ",
    "comune",
    "",
    "creta",
    "spagna",
    "sicilia",
    "langa",
    "regione",
    "isola",
    "borotalco spray intensive",
    "fagioli borlotti",
    "pasta farfalle",
    "pasta fusilli",
    "pasta per lasagne",
    "piselli medi",
    "uova 10 medie",
    "actimel pesca e pappa reale ",
    "actimel frutti di bosco ",
    "actimel multifrutti ",
    "prosciutto cotto",
    "gnocchetti",
    "wustel",
    "mozzarella",
    "yogurt caffè ",
    "burro",
    "yogurt nocciola ",
    "yogurt pistacchio ",
    "yogurt cereale ",
    "yogurt vaniglia ",
    "lenticchie",
    "baiocchi",
    "caffè crema e gusto",
    "latte parzialmente scremato",
    "succo alla pera",
    "tacchino",
    "thè pesca",
    "amaretti",
    "tonno",
    "alici",
    "ritornello",
    "pangrattato",
    "cracker",
    "pavesini",
    "fette biscottundefinede ",
    "rusticotte",
    "pastefrolle",
    "rubatà",
    "borotalco",
    "ricotta",
    "philadelphia",
    "panna",
    "pane in cassetta",
    "fettine",
    "chicche di patate",
    "salmone affumicato",
    "actimel agrumi ",
    "yogurt misti ",
    "nutella biscuits",
    "pandoro tartufato",
    "penne rigate n.73",
    "duo chocolate",
    "grand ferrero rocher",
    "lenticchie verde pugliesi ",
    "pane per tramezzini",
    "yogurt stracciatella ",
    "yogurt cocco ",
    "yogurt frutta e cereale ",
    "fagioli di spagna",
    "mortadella",
    "prosciutto crudo",
    "insalata di mar ",
    "bastoncini di merluzzo ",
    "merluzzo gratinato",
    "cotolette con spinaci ",
    "cotoletta di pollo ",
    "merluzzo alla griglia",
    "burger",
    "bastoncini di surimi ",
    "patatine classiche",
    "frollini integrali",
    "carota",
    "mela",
    "petto di pollo ",
    "formaggio spalmabile",
    "arrosto di tacchino ",
    "salame",
    "sugo pronto",
    "pesto",
    "lattuga",
    "pomodoro",
    "fontal",
    "caffè",
    "biscotto novellini ",
    "pasta",
    "ceci",
    "pollo arrosto ",
    "zucchini",
    "olio",
    "biscotto",
    "ghiacciolo",
    "uova",
    "dentifricio",
    "deodorante",
    "spazzolino",
    "crema solare 50+",
    "crema solare 30",
    "rucola",
    "banana",
    "yogurt",
    "piselli fini",
    "disinfettante per sanitari",
    "ombrellone da spiaggia",
    "carta igienica ",
    "sale grosso",
    "fermatenda",
    "tenda oscurante ",
    "tenda filtrante ",
    "bastone per tenda ",
    "gel lavastoviglie ",
    "acchiappa colori ",
    "coca cola",
    "tè freddo al limone",
    "tè freddo alla pesca",
    "gel wc",
    "sgrassatore universale",
    "spray anticalcare bagno",
    "insalata",
    "formaggio",
    "carne",
    "maionese",
    "avocado",
    "maasdam",
    "dentifricio al carbone ",
    "disgorgante gel",
    "ace",
    "uva",
    "albicocca",
    "foglie di vite ripiene",
    "insalata gentile",
    "carta da forno ",
    "pasta fillo ",
    "involtini primavera",
    "salsa di soia",
    "verza",
    "macinato di carne",
    "fragola",
    "cavolo cappuccio",
    "mascarpone senza lattosio",
    "mascarpone",
    "panna senza lattosio",
    "mirtillo",
    "crema al mascarpone",
    "ravioli cinesi",
    "torta con mascarpone e frutta ",
    "tortilla de patatas",
    "churros",
    "empanadas",
    "paella",
    "savoiardo",
    "tacos",
    "cocktail",
    "metodo di pagamento",
    "satispay",
    "paypal",
    "contante",
    "bonifico",
    "bollettino postale",
    "carta di credito ",
    "bancomat",
    "assegno",
    "buono",
    "yap",
    "prepagata",
    "bancomatpay",
    "mav",
    "check out",
    "via",
    "palazzo",
    "statua",
    "strada",
    "edificio",
    "affresco",
    "stazione",
    "piazza",
    "la casa de los gatos ",
    "monumento",
    "ghost whisperer",
    "scandal",
    "profiling",
    "blanca",
    "ricetta",
    "the glory",
    "unbelievable",
    "torrone",
    "mercato coperto",
    "mercato",
    "tatuatore",
    "farina di riso",
    "lievito di birra secco",
    "lundefinede senz lattosio ",
    "sciroppo alla menta ",
    "pellicola trasparente",
    "anguria",
    "melone giallo",
    "bao buns",
    "zafferano",
    "caffè decaffeinato ",
    "crema al cioccolato e nocciola",
    "gomma da masticare",
    "aceto di vino bianco ",
    "semi di sesamo",
    "sgrassatore superfici alimentari",
    "sottilette cheddar",
    "pane per burger",
    "ospedale santo spirito ",
    "ospedale maria vittoria ",
    "cheesecake",
    "sentiero",
    "basilica di superga ",
    "cupola",
    "tombe",
    "architettura",
    "arredamento",
    "lidia poet",
    "ventilatore",
    "carcere",
    "cuffie",
    "metropolitana",
    "sushi okami",
    "blu paradise",
    "merenda",
    "pasto",
    "biscotto con grano saraceno e cioccolato ",
    "biscotti al cioccolato ",
    "smoothie sostitutivi di pasti",
    "sale lavastoviglie ",
    "drago e la fata",
    "ritirare esiti ",
    "giardiniera",
    "matrimonio",
    "cappella",
    "spaccanapoli",
    "attività",
    "paesedellebuste",
    "cous cous",
    "pesce",
    "nastro adesivo",
    "pepco",
    "pasta integrale",
    "cozze",
    "gamberetto",
    "corso di formazione",
    "contenitore",
    "sacchetto per congelare",
    "fertilizzante",
    "bones",
    "pane",
    "frutto",
    "torta",
    "verdura",
    "salsa",
    "versamento",
    "torta paradiso",
    "igiene",
    "prelievo",
    "ristorante tailandese ",
    "yo yogurt",
    "berlicabarbis",
    "gelateria",
    "iscrizione",
    "marmellata alle pesche",
    "ristorante indiano ",
    "basko",
    "ondaland",
    "parco acquatico",
    "ammorbidente",
    "detersivo lavatrice",
    "fagiolini",
    "margarina",
    "scamorza affumicata",
    "stracchino",
    "candeggina delicata ",
    "palio",
    "pizzburg",
    "condominio",
    "tv",
    "la mia prediletta",
    "sushi samurai",
    "elemental",
    "farina",
    "cheese",
    "resto",
    "centro",
    "candeggina",
    "zucchero",
    "trapizzino",
    "crema pasticcera",
    "crostata",
    "cipolla",
    "punto panoramico",
    "insalata valeriana",
    "anime false",
    "cambiate le lenzuola ",
    "dolore",
    "denaro",
    "classe",
    "verifica",
    "laboratorio",
    "marconi",
    "maxwell",
    "plc",
    "pascal",
    "turing",
    "tolomeo",
    "newton",
    "associazione",
    "chiacchere",
    "rievocazione storica",
    "teatro",
    "cavolfiore",
    "biscotto integrale ",
    "hamburger di bovino ",
    "udon",
    "egri danza",
    "riunione",
    "la padella",
    "polenta",
    "manhattan",
    "neve",
    "spezia",
    "the diplomat",
    "orientament",
    "biblioteca",
    "parrucchiere",
    "consiglio",
    "colloquio",
    "scrutinio",
    "laplace",
    "spinaci",
    "eulero",
    "instagram contest",
    "settore",
    "scuola",
    "liceo",
    "sostituzione",
    "uscita",
    "fazzoletto",
    "tovaglioli",
    "palestra",
    "mcfit",
    "olio d'oliva",
    "patate al forno ",
    "lavato accappatoio",
    "divano",
    "granita",
    "batteri",
    "passaggi",
    "passo",
    "segreteria",
    "pane proteico ",
    "pane ai 6 cereali ",
    "formazione",
    "conferenza",
    "aula magna ",
    "correzione",
    "focaccia",
    "rosmarino",
    "portale",
    "telefono",
    "torta alla zucca ",
    "focaccia di zucca ",
    "ritirare",
    "officundefineda della scrittura ",
    "ristorante arabo ",
    "designated survivor",
    "primosale",
    "origano",
    "pasta cavatappi",
    "pasta elicoidali",
    "farina 00",
    "farina di manitoba ",
    "al andalus",
    "sagra",
    "rifugio jervis",
    "compito",
    "dipartimento",
    "gita",
    "portare",
    "zucca",
    "pilates",
    "frittata",
    "frittata al forno ",
    "verifica di recupero ",
    "pcto",
    "encanto",
    "ora libera",
    "assemblea",
    "pastina",
    "minestra",
    "minestrina",
    "minestrone",
    "la sirenetta",
    "ingredienti",
    "fiera",
    "stanza",
    "bancarella",
    "sale fino",
    "pepe bianco",
    "pepe nero",
    "lievito per dolci",
    "cornetto",
    "collegio docenti",
    "nonna",
    "nonno",
    "teatro monterosa",
    "stampare",
    "marca da bollo",
    "comprare",
    "moulin",
    "passeggiata",
    "gorgonzola dolce",
    "titolo di studio ",
    "laurea",
    "concerto",
    "grammatica",
    "preposizione",
    "in",
    "ballare",
    "notte",
    "dei",
    "ricercare",
    "del",
    "di",
    "halloween",
    "office",
    "programmazione",
    "elezioni",
    "corsa",
    "videochiamata",
    "i bastardo di pizzofalcone ",
    "patatine rustiche",
    "brie",
    "pulizia",
    "bombardino",
    "beige",
    "castagna",
    "bosco",
    "ghilot",
    "occitan",
    "sfilare",
    "menù",
    "pizza",
    "calzone",
    "torta salata",
    "cereale",
    "farro",
    "oliva",
    "radicchio",
    "pancetta",
    "spago",
    "pasta sfoglia",
    "cucinare",
    "per",
    "caramella",
    "dolce",
    "patatine paprika",
    "cornetti di mais ",
    "succo frutti rossi",
    "succo",
    "thè limone",
    "birra",
    "audizioni",
    "market yang guang",
    "gnocchi cinesi",
    "pubblicazione",
    "offerta",
    "articolo",
    "un",
    "mamma",
    "crepes",
    "spinacine",
    "sacchetti per spazzatura",
    "good",
    "witch",
    "palcoscenico",
    "tablao",
    "flamenco",
    "tor",
    "animale",
    "astro",
    "luna",
    "congiunzione",
    "contatto",
    "email",
    "polpetta",
    "aspirapolvere",
    "giovinezza",
    "età",
    "aggettivo",
    "etern",
    "san",
    "sant",
    "cambiare",
    "gomma",
    "spostament",
    "limone",
    "vetro",
    "materiale",
    "aggiornamento",
    "programma",
    "ingrassare",
    "portone",
    "simone",
    "termosifone",
    "riscaldament",
    "verbo",
    "preventivo",
    "documento",
    "cavo",
    "compleanno",
    "hunger",
    "games",
    "riso",
    "erbetta",
    "errore",
    "il",
    "nuovo",
    "istruttore",
    "amare",
    "sentimento",
    "sostantivo",
    "cucina",
    "curry",
    "pronome",
    "ce",
    "bruciare",
    "manutenzione",
    "stampante",
    "adattare",
    "adattatore",
    "pasta al forno ",
    "forno",
    "aceto",
    "vino",
    "bianco",
    "colore",
    "actimel",
    "agrume",
    "acchiappare",
    "pesca",
    "grano",
    "reale",
    "arrosto",
    "bastoncino",
    "merluzzo",
    "surimi",
    "tenda",
    "con",
    "cioccolato",
    "integrale",
    "fagiolo",
    "lavastoviglie",
    "gel",
    "sale",
    "cocco",
    "nocciola",
    "pistacchio",
    "stracciatella",
    "vaniglia",
    "lenzuolo",
    "delicato",
    "carta",
    "da",
    "credito",
    "libro",
    "mais",
    "giappone",
    "esito",
    "dirigente",
    "patata",
    "dominio",
    "papà",
    "lingua",
    "spirito",
    "croce",
    "piemonte",
    "valle",
    "recuperare",
    "passata di pomodoro ",
    "carbone",
    "cotoletta",
    "pollo",
    "petto",
    "corpo",
    "olio di semi ",
    "seme",
    "mandarino",
    "succo arancia rossa",
    "succo alla pesca",
    "mostra",
    "clementina",
    "rosso",
    "cipolla rossa ",
    "calza",
    "lungo",
    "calze lunghe ",
    "riso basmati ",
    "pane integrale ",
    "versione",
    "permettere",
    "salvare",
    "ottimizzare",
    "salvataggio",
    "pigna",
    "pino",
    "albero",
    "apprendista",
    "strega",
    "deumidificatore",
    "bastardo",
    "dispensa",
    "pan carrè",
    "cordon bleu",
    "sgombro",
    "shopping",
    "f24",
    "agenzia delle entrate ",
    "rifiuto",
    "istanze online",
    "vicino",
    "traforare",
    "frejus",
    "corso",
    "inghilterra",
    "minuto",
    "polvere",
    "entrare",
    "hotel",
    "lezione",
    "dimostrare",
    "avverbio",
    "non",
    "galleria",
    "ponte",
    "vecchio",
    "nazione",
    "spazio",
    "battistero",
    "novella",
    "storia",
    "torre",
    "fiore",
    "ritornare",
    "progetto",
    "curriculum vitae",
    "andare",
    "autogrill",
    "tappa",
    "purè",
    "brioche",
    "parola",
    "raclettes",
    "ogni",
    "ha",
    "qualcosa",
    "caratteristico",
    "caccia",
    "tesoro",
    "tisana",
    "camper",
    "tartines",
    "tunnel",
    "primo",
    "piano",
    "caminio",
    "gigante",
    "terzo",
    "arte",
    "poi",
    "contemporanea",
    "antico",
    "paesaggio",
    "bagno",
    "vaso",
    "gioco",
    "parchimetro",
    "prigione",
    "magnete",
    "francia",
    "liquida",
    "fonduta",
    "tanto",
    "regolare",
    "introdotto",
    "poco",
    "gustare",
    "natale",
    "caldo",
    "tartare",
    "salmone",
    "latte",
    "donare",
    "comunitá",
    "italia",
    "presepe",
    "cantare",
    "lago",
    "mare",
    "fontana",
    "elefante",
    "chiostro",
    "anello",
    "percorso",
    "segnalare",
    "piccolo",
    "sono",
    "molto",
    "vicolo",
    "ma",
    "meglio",
    "alcuno",
    "caso",
    "km",
    "s",
    "riuscire",
    "finire",
    "più",
    "passerella",
    "chiuso",
    "sopraelevare",
    "capra",
    "cavallo",
    "spoglio",
    "internare",
    "stupendo",
    "tutto",
    "affrescare",
    "foto",
    "montagna",
    "processione",
    "iniziare",
    "messa",
    "rimanere",
    "stare",
    "dentro",
    "visitare",
    "cortile",
    "completare",
    "su",
    "prenotare",
    "richiedere",
    "tempo",
    "piatto",
    "tipico",
    "ovviamente",
    "gli",
    "er",
    "pieno",
    "enorme",
    "spiegare",
    "applicare",
    "diversa",
    "enigma",
    "semplice",
    "sera",
    "pioggia",
    "statale",
    "musica",
    "piccante",
    "nessun",
    "pedaggio",
    "pagare",
    "scaricare",
    "ricevere",
    "rimborsare",
    "male",
    "mancare",
    "super",
    "separare",
    "riunire",
    "livellare",
    "consistenza",
    "nulla",
    "tiglio",
    "desinenza",
    "diminutivo",
    "vezzeggiativo",
    "peggiorativo",
    "accrescitivo",
    "abitante",
    "dispregiativo",
    "suffisso nominale",
    "gestone",
    "bando",
    "baguette",
    "asiago",
    "grazie",
    "metodo",
    "eliminare",
    "devastare",
    "pianeta",
    "incontro",
    "ciò",
    "insieme",
    "solito",
    "problema",
    "comunicare",
    "antipasto",
    "salare",
    "impasto",
    "aglio",
    "cappero",
    "alloro",
    "acciuga",
    "brasile",
    "ristorante brasilian ",
    "decorazione",
    "luce",
    "accademia",
    "durare",
    "convento",
    "medico",
    "prendere",
    "pacco",
    "tartufo",
    "rosa",
    "abbazia",
    "monte",
    "aggiungere",
    "aggiunto",
    "troppo",
    "perché",
    "sentire",
    "momento",
    "silenziare",
    "docente",
    "solo",
    "collegare",
    "economia",
    "forse",
    "guidare",
    "ingresso",
    "successivo",
    "vedere",
    "preso",
    "villa",
    "paninoteca",
    "gratuito",
    "escluso",
    "invece",
    "chivas",
    "arrivare",
    "capodanno",
    "lingotto",
    "salsiccia",
    "crema",
    "besciamella",
    "gratuggiare",
    "formaggio gratuggiato ",
    "salvia",
    "fresco",
    "lasagna",
    "peperone",
    "grissino",
    "formaggio pasta filata  ",
    "verdesca",
    "link",
    "aprire",
    "aperto",
    "camomilla",
    "stendere",
    "tagliare",
    "metà",
    "condire",
    "arrotolare",
    "punteggiatura",
    "avere",
    "ho",
    "mano",
    "spianatoia",
    "meno",
    "appiccicare",
    "mattina",
    "macchina",
    "scaldare",
    "prequel",
    "dovere",
    "partire",
    "ora",
    "ritardo",
    "abbia",
    "decidere",
    "deciso",
    "mangiare",
    "tornare",
    "soggiorno",
    "scansionare",
    "camera",
    "secondo",
    "balcone",
    "cui",
    "campana",
    "come",
    "nel",
    "gobbo",
    "repubblica",
    "borgo",
    "indipendenza",
    "veramente",
    "spendere",
    "me",
    "aspettare",
    "porzione",
    "grande",
    "altrimenti",
    "leggero",
    "intero",
    "etnia",
    "genere",
    "locale",
    "carino",
    "volta",
    "mattone",
    "ripiena",
    "quadro",
    "tavolo",
    "figura",
    "video",
    "illustrare",
    "maestoso",
    "ricco",
    "pala",
    "altare",
    "superiore",
    "cella",
    "religioso",
    "struttura",
    "particolare",
    "essere",
    "foss",
    "interessante",
    "temporaneamente",
    "cenacolo",
    "anche",
    "comparire",
    "dormire",
    "ultimo",
    "schiacciata",
    "prosciutto",
    "fontina",
    "cantucci",
    "relax",
    "proposta",
    "barca",
    "contenere",
    "sabbia",
    "raffigurare",
    "onda",
    "riempire",
    "nostro",
    "dopo",
    "preparare",
    "giovane",
    "gentile",
    "visto",
    "panino",
    "viscido",
    "stomaco",
    "vitello",
    "tra",
    "quello",
    "martello",
    "bello",
    "sacrestia",
    "sotteraneo",
    "croissant",
    "friabile",
    "ricchezza",
    "spettacolare",
    "cripta",
    "coda",
    "impressionare",
    "intanto",
    "presentare",
    "opera",
    "famoso",
    "piramide",
    "zaino",
    "devo",
    "soffitto",
    "restaurare",
    "dietro",
    "bruschetta",
    "pazzo",
    "facciata",
    "terminare",
    "usare",
    "fondalee",
    "cinghiale",
    "traduzione",
    "fortuna",
    "strofinare",
    "naso",
    "raviolo",
    "gnocco",
    "spaghetto",
    "sorgente",
    "belvedere",
    "fare",
    "calamita",
    "scendiletto",
    "panforte",
    "studiare",
    "biro",
    "follia",
    "fantasma",
    "giorno",
    "mercoledì",
    "mese",
    "gennaio",
    "richiesta",
    "fattura",
    "permesso",
    "workshop",
    "sformare",
    "pelle",
    "dermatologica",
    "chiedere",
    "spalla",
    "neo",
    "prudere",
    "computer",
    "schermo",
    "tiramisù",
    "tessera",
    "patrimon",
    "tartufigeno",
    "eserciz",
    "autovelox",
    "dividere",
    "albume",
    "tuorlo",
    "immergere",
    "disporre",
    "pirofila",
    "coprire",
    "continuare",
    "esaurire",
    "stufare",
    "cercare",
    "trattenere",
    "istinto",
    "modo",
    "potere",
    "niente",
    "perdonare",
    "oggi",
    "dubbio",
    "nascere",
    "sognare",
    "ne",
    "accendere",
    "venire",
    "attaccare",
    "nero",
    "caricare",
    "controllare",
    "login",
    "menu",
    "utente",
    "bloccare",
    "lasciare",
    "chiamare",
    "lieve",
    "inferiore",
    "rispettare",
    "voto",
    "parlare",
    "modulo",
    "insegnare",
    "rispondere",
    "risposta",
    "rock",
    "yoga",
    "annullare",
    "avis",
    "esame",
    "vuoto",
    "ottimo",
    "bene",
    "capacità",
    "base",
    "fastfood",
    "piaciere",
    "trovare",
    "assaggiare",
    "appena",
    "nudo",
    "difficile",
    "carro",
    "movimento",
    "rievocare",
    "scarpa",
    "sfizio",
    "hamburger",
    "bovino",
    "proteina",
    "lattosio",
    "officio",
    "scrittura",
    "aula",
    "negozio",
    "scelta",
    "redare",
    "elenco",
    "gruppo",
    "indicare",
    "disponibile",
    "clinica",
    "password",
    "rata",
    "prestare",
    "analizzare",
    "estratto",
    "conto",
    "team",
    "cittadella",
    "confrontare",
    "transazione",
    "concluso",
    "nomina",
    "tema",
    "registro",
    "dado",
    "quanto",
    "creare",
    "maturità",
    "materia",
    "esterno",
    "visualizzare",
    "intervento",
    "bresaola",
    "rotolare",
    "crosta",
    "scadenza",
    "inviare",
    "kiwi",
    "pera",
    "cuocere",
    "cott",
    "speck",
    "prezzemolo",
    "budino",
    "philadelphia senza lattosio",
    "caffè in grani",
    "gelatina in fogli",
    "vanillina",
    "crostino",
    "sportello",
    "gnocchi ripieni ",
    "sciroppo",
    "gelatina",
    "freddo",
    "pentola",
    "mescolare",
    "strizzare",
    "versare",
    "stampo",
    "riposare",
    "almeno",
    "frigo",
    "farcire",
    "mettere",
    "sciogliere",
    "bagnomaria",
    "scolare",
    "mattarello",
    "sottile",
    "chiudere",
    "pergamena",
    "velo",
    "organizzare",
    "sorpresa",
    "salato",
    "provare",
    "schiuma",
    "sopra",
    "buccia",
    "spelare",
    "grado",
    "tardo",
    "esperimento",
    "download",
    "ieri",
    "augurare",
    "messaggiare",
    "comunque",
    "ancora",
    "segno",
    "accesso",
    "elaborare",
    "preferire",
    "manuale",
    "giustificare",
    "già",
    "continente",
    "africa",
    "carta docente ",
    "giornale",
    "povero",
    "creatura",
    "interrotto",
    "scala",
    "condonare",
    "aggiornare",
    "firmare",
    "griglia",
    "ricevuta",
    "chi",
    "pdf",
    "vestire",
    "otturazione",
    "dente",
    "condivisione",
    "ansia",
    "dinamica",
    "preliminare",
    "verde",
    "fetta",
    "prodotto",
    "centrale",
    "karaoke",
    "legno",
    "piadina",
    "palco",
    "posto",
    "po'",
    "pancia",
    "fuori",
    "orizzonte",
    "vertice",
    "accorpare",
    "valutare",
    "visione",
    "piattaforma",
    "ministero",
    "inserire",
    "catena",
    "bici",
    "consul",
    "mollusco",
    "vongola",
    "scongelare",
    "padella",
    "pulire",
    "numero",
    "mille",
    "esercitare",
    "definire",
    "riparare",
    "togliera",
    "tolto",
    "danneggiare",
    "diretto",
    "complicare",
    "capuccino",
    "dalla",
    "simpatico",
    "intelligente",
    "discussione",
    "discoteca",
    "mediterraneo",
    "civico",
    "guardaroba",
    "soffice",
    "fantastico",
    "veloce",
    "dee jay ",
    "bravo",
    "sicurezza",
    "sasso",
    "annoiare",
    "certo",
    "pure",
    "fuggire",
    "fuga",
    "ambiente",
    "ambientare",
    "simile",
    "differenza",
    "lama",
    "cronaca",
    "mondo",
    "emerso",
    "giudice",
    "guerra",
    "candido",
    "cocaina",
    "perfetto",
    "locanda",
    "leggenda",
    "nido",
    "ragno",
    "maschera",
    "strage",
    "massacro",
    "labirinto",
    "rivelare",
    "città",
    "bestia",
    "regno",
    "drago",
    "foresta",
    "ritrovare",
    "germania",
    "calendario",
    "piangere",
    "felice",
    "commozione",
    "cancellare",
    "metro",
    "puntata",
    "sembrare",
    "prevalere",
    "rapido",
    "appassire",
    "duna",
    "passaporto",
    "commissario",
    "appuntamento",
    "test",
    "invalsi",
    "istruzione",
    "somministrare",
    "svenire",
    "scendere",
    "cadere",
    "rima",
    "incastrare",
    "corrimano",
    "opposto",
    "discesa",
    "uscire",
    "quasi",
    "server",
    "browser",
    "capire",
    "antivirus",
    "convincere",
    "convinto",
    "barzelletta",
    "utero",
    "imprenditrice",
    "odontotecnico",
    "agricolo",
    "complimento",
    "attraversare",
    "sulla",
    "striscia",
    "armadio",
    "scatola",
    "cellulare",
    "scorrere",
    "scorso",
    "due",
    "mandare",
    "garanzia",
    "scontrino",
    "sbagliare",
    "qualche",
    "panico",
    "media",
    "rimandare",
    "vice",
    "risparmiare",
    "intercedere",
    "abbinare",
    "qual",
    "figlio",
    "quando",
    "questo",
    "neanche",
    "iscrivere",
    "iscritto",
    "pescheria",
    "girare",
    "perderere",
    "esibire",
    "contorsione",
    "quattro",
    "braccia",
    "gamba",
    "scenografia",
    "travestire",
    "notizia",
    "fac",
    "copiare",
    "incollare",
    "femmina",
    "noi",
    "ape",
    "indovinare",
    "cima",
    "tre",
    "possibile",
    "online",
    "lunghezza",
    "campo",
    "ammorbidire",
    "mollica",
    "ciotola",
    "pepe",
    "formare",
    "palla",
    "rosolare",
    "conserva",
    "allungare",
    "fuoco",
    "basso",
    "piede",
    "destro",
    "cominciare",
    "calzatura",
    "ciabatta",
    "infradito",
    "sinistro",
    "cantone",
    "pisello",
    "soia",
    "lavare",
    "filo",
    "strapazzare",
    "finestra",
    "curcuma",
    "saltare",
    "brodo",
    "burro",
    "segreto",
    "silente",
    "nevicare",
    "mezzo",
    "impossibile",
    "realtà",
    "centimetro",
    "america",
    "quindi",
    "fungo",
    "rompere",
    "rotto",
    "manubrio",
    "sessione",
    "sezione",
    "risultato",
    "sintesi",
    "riassunto",
    "riepilogo",
    "fotografo",
    "scena",
    "lamentare",
    "assegnare",
    "multiplo",
    "ordinare",
    "tentare",
    "frenare",
    "decretare",
    "bisognare",
    "scheda",
    "sim",
    "credenziale",
    "errato",
    "cucire",
    "tuta",
    "pantalone",
    "sperare",
    "tenere",
    "accompagnare",
    "occhio",
    "oculista",
    "sorbetto",
    "sostituire",
    "battuta",
    "pazienza",
    "straordinario",
    "proiezione",
    "volare",
    "università",
    "artificio",
    "domanda",
    "complesso",
    "competizione",
    "olimpiadi",
    "scorza",
    "bollire",
    "ebollizione",
    "spegnere",
    "amalgamare",
    "funzione",
    "risoluzione",
    "costituire",
    "costituzione",
    "barocco",
    "modificare",
    "anagrafe",
    "studente",
    "ruota",
    "concorso",
    "pubblicità",
    "montare",
    "titolo",
    "informazione",
    "prezzo",
    "anteprima",
    "interruzione",
    "sella",
    "broccolo",
    "risolvere",
    "risolto",
    "correggere",
    "corretto",
    "dizionario",
    "pasqua",
    "tirare",
    "posizionare",
    "arredare",
    "commuovere",
    "commosso",
    "lettera",
    "suscitare",
    "applauso",
    "benedire",
    "ramo",
    "benefico",
    "composto",
    "pelare",
    "pezzo",
    "ungere",
    "teglia",
    "girarrosto",
    "ulivo",
    "temporaneo",
    "tappeto",
    "terrazza",
    "bonsai",
    "sviluppare",
    "ceramica",
    "inglese",
    "adorare",
    "tè",
    "litchi",
    "passion fruit ",
    "sedia",
    "trono",
    "arma",
    "spada",
    "asciutto",
    "abbondante",
    "tag",
    "astrofisica",
    "seguire",
    "normale",
    "scacco",
    "desiderare",
    "vivere",
    "informatica",
    "scoprire",
    "scoperto",
    "volere",
    "vuole",
    "pompiere",
    "sport",
    "basket",
    "arrampicare",
    "lavorare",
    "credere",
    "relativo",
    "stress",
    "trasferire",
    "barbera",
    "malattia",
    "diarrea",
    "referto",
    "analisi",
    "sangue",
    "mentre",
    "smettere",
    "anticipo",
    "caparra",
    "tranquillo",
    "frequentare",
    "inoltrare",
    "incaricare",
    "ruolo",
    "stagione",
    "pavimento",
    "coscia",
    "costa",
    "toma",
    "consegnare",
    "vocalie",
    "distanza",
    "infilare",
    "strumento",
    "asparago",
    "sushi",
    "rifornire",
    "fornit",
    "intelligenza",
    "clima",
    "quartiere",
    "luogo",
    "politecnico",
    "infatti",
    "conoscere",
    "arcobaleno",
    "nobile",
    "immersivo",
    "natura",
    "vorr",
    "commerciare",
    "specchio",
    "abito",
    "compilare",
    "foglio",
    "emoglobina",
    "capello",
    "bigodo",
    "detergente",
    "occupare",
    "restituire",
    "sono stati condonati ",
    "raggiungere",
    "diabete",
    "migrare",
    "client",
    "procedura",
    "componente",
    "grafica",
    "pizzoccheri",
    "caciotta",
    "imburrareare",
    "sbattere",
    "temperatura",
    "emozione",
    "gioia",
    "immediato",
    "ragionare",
    "rabbia",
    "paura",
    "tristezza",
    "disgusto",
    "agli",
    "ideare",
    "vergognare",
    "orgoglio",
    "stimolare",
    "senso",
    "sensazione",
    "appagare",
    "protezione",
    "cover",
    "granola",
    "miele",
    "pace",
    "preoccupare",
    "futuro",
    "costruire",
    "innaugurare",
    "tecnologia",
    "terra",
    "elettricità",
    "corrente",
    "spento",
    "illuminare",
    "colonna",
    "euro",
    "tritare",
    "friggere",
    "stage",
    "cortometraggio",
    "circa",
    "pannello",
    "confermare",
    "biennale",
    "pensare",
    "semaforo",
    "ludico",
    "animare",
    "avviare",
    "teoria",
    "addestrare",
    "riconoscere",
    "immagine",
    "introverso",
    "principale",
    "accelerare",
    "legume",
    "misto di legume e cereali ",
    "perini rossi ",
    "bran flakes",
    "soffiare",
    "riso soffiato ",
    "cipro",
    "halloumi",
    "tradizione",
    "nome",
    "marca",
    "derby",
    "crudo",
    "smart",
    "letto",
    "codice",
    "barcode",
    "leggere",
    "religione",
    "telecomunicazione",
    "urologo",
    "andrologo",
    "urinare",
    "maschio",
    "galileo",
    "traviare",
    "settimana",
    "cuscino",
    "suonare",
    "spiazzare",
    "redattore",
    "produttore",
    "mastio",
    "girasole",
    "semi di girasole ",
    "riservare",
    "fabbrica",
    "dipinto",
    "rappresentare",
    "profondo",
    "sospeso",
    "valore",
    "secco",
    "sar",
    "fermare",
    "incorporare",
    "zuppa",
    "adesso",
    "now",
    "anzi",
    "dottore",
    "podere",
    "dimenticare",
    "sabato",
    "apple",
    "imponente",
    "accanto",
    "coinvolgere",
    "entusiasm",
    "esemplare",
    "medesimare",
    "uguale",
    "stess",
    "veicolo",
    "trainare",
    "carrozza",
    "subito",
    "cielo",
    "limpido",
    "diventare",
    "pomeriggio",
    "confezionare",
    "bibita",
    "soldo",
    "avanzare",
    "indagare",
    "mandorla",
    "crescere",
    "appartamento",
    "felpa",
    "mappa",
    "partecipare",
    "robot",
    "matematica",
    "tè nero ",
    "tessuto",
    "orecchio",
    "orecchiette",
    "ananas",
    "succo ananas ",
    "insetto",
    "farfalla",
    "parroco",
    "barba",
    "babbo",
    "predicare",
    "causa",
    "sciopero",
    "migliorare",
    "selezionare",
    "pappa",
    "portafoglio",
    "lituania",
    "privare",
    "calciare",
    "avvertire",
    "martedì",
    "marcatore",
    "sovrapposto",
    "spaccare",
    "saga",
    "avvocato",
    "sterilizzare",
    "affollare",
    "riflettere",
    "riflessione",
    "qrcode",
    "riferire",
    "buffet",
    "concreto",
    "vero",
    "salume",
    "denso",
    "agnolotto",
    "lampone",
    "liquirizia",
    "guancia",
    "fronte",
    "cerimonia",
    "celebrare",
    "prete",
    "baciare",
    "danza",
    "casquè",
    "coetaneo",
    "catering",
    "assistente",
    "poltrona",
    "convivere",
    "infermiere",
    "soprattutto",
    "davanti",
    "terreno",
    "congiuntivo",
    "periodo",
    "panchina",
    "accorgere",
    "accorto",
    "sempre",
    "riguardare",
    "formalizzare",
    "confondere",
    "confusion",
    "scontrare",
    "battaglia",
    "filtrare",
    "descrivere",
    "descrizion",
    "oscurare",
    "vettore",
    "shampoo",
    "educare",
    "ciliegia",
    "mango",
    "melanzana",
    "camicia",
    "arachide",
    "crostaceo",
    "visivo",
    "frase",
    "acconsentire",
    "commentare",
    "svolgere",
    "svolto",
    "ingegnere",
    "editor",
    "personalizzare",
    "festival",
    "vissuto",
    "chimica",
    "taciturno",
    "fisica",
    "novembre",
    "polpo",
    "uccello",
    "fenice",
    "raccogliere",
    "raccolto",
    "automatico",
    "costrutto",
    "chiarire",
    "circolare",
    "ufficio",
    "privacy",
    "scottare",
    "collo",
    "gola",
    "soluzione",
    "firefox",
    "intercettare",
    "cursore",
    "protetto",
    "coro",
    "nominativo",
    "abbastanza",
    "scomodare",
    "database",
    "simulare",
    "pronto",
    "panno",
    "cinque"
];
var alfabeto = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z"
];
let vetParFacile = [];
let vetParMedio = [];
let vetParDifficile = [];
function init(){
    //Divisione parole per difficoltà
    let j = 0, k = 0, l = 0;
    for(let i = 0; i < vetParole.length; i++)
    {
        if(vetParole[i].length <= 6){
            vetParFacile[j] = vetParole[i];
            j++;
        }
        else if(vetParole[i].length >= 12){
            vetParDifficile[k] = vetParole[i];
            k++;
        }
        else{
            vetParMedio[l] = vetParole[i];
            l++;
        }
    }

    //caricamento alfabeto
    for(let i = 0; i < alfabeto.length; i++)
    {
        let article = document.createElement('article');
        article.innerText = alfabeto[i];
        article.onclick = clickLettera;
        document.getElementById("secLettere").appendChild(article);
    }
}
let partiteFacile = 0, partiteMedio = 0, partiteDifficile = 0;
let parola = "";
function clickFacile(){
    document.getElementById("secParolaNascosta").innerHTML = " ";
    parola = vetParFacile[Math.round(Math.random()*(vetParFacile.length))];
    for(let i = 0; i < parola.length; i++)
    {
        let article = document.createElement('article');
        article.innerText = '_';
        article.id= i;
        document.getElementById("secParolaNascosta").appendChild(article);
    }
    partiteFacile++;
    console.log(parola);
}
function clickMedio(){
    if(partiteFacile == 0)
        alert("Devi fare almeno una partita nel livello facile");
    else{
        document.getElementById("secParolaNascosta").innerHTML = " ";
        parola = vetParMedio[Math.round(Math.random()*(vetParMedio.length))];
        for(let i = 0; i < parola.length; i++)
        {
            let article = document.createElement('article');
            article.innerText = '_';
            article.id= i;
            document.getElementById("secParolaNascosta").appendChild(article);
        }
        partiteMedio++;
        console.log(parola);
    }
}
function clickDifficile(){
    if(partiteFacile == 0 || partiteMedio == 0)
        alert("Devi fare almeno una partita nel livello medio");
    else{
        document.getElementById("secParolaNascosta").innerHTML = " ";
        parola = vetParDifficile[Math.round(Math.random()*(vetParDifficile.length))];
        for(let i = 0; i < parola.length; i++)
        {
            let article = document.createElement('article');
            article.innerText = '_';
            article.id= i;
            document.getElementById("secParolaNascosta").appendChild(article);
        }
        partiteDifficile++;
        console.log(parola);
    }
}
let nTent = 0;
function clickLettera(){
    let letteraPrem = event.currentTarget.innerText.toLowerCase();
    let n = 0;
    if(parola.includes(letteraPrem) == true){
        n = parola.indexOf(letteraPrem);
        document.getElementById(n).innerText = letteraPrem;
    }
    else{
        nTent++;
    }
    if(nTent == 4){
        alert("Hai Perso");
    }
}